const MASTER_TICKERS = [
    // --- INDIA (NSE 100 Major) ---
    { s: "RELIANCE.NS", n: "Reliance Industries Ltd" },
    { s: "TCS.NS", n: "Tata Consultancy Services" },
    { s: "HDFCBANK.NS", n: "HDFC Bank Ltd" },
    { s: "ICICIBANK.NS", n: "ICICI Bank Ltd" },
    { s: "INFY.NS", n: "Infosys Ltd" },
    { s: "SBIN.NS", n: "State Bank of India" },
    { s: "BHARTIARTL.NS", n: "Bharti Airtel Ltd" },
    { s: "ITC.NS", n: "ITC Ltd" },
    { s: "LICI.NS", n: "Life Insurance Corp" },
    { s: "HINDUNILVR.NS", n: "Hindustan Unilever" },
    { s: "LT.NS", n: "Larsen & Toubro" },
    { s: "TATAMOTORS.NS", n: "Tata Motors" },
    { s: "TATASTEEL.NS", n: "Tata Steel" },
    { s: "AXISBANK.NS", n: "Axis Bank" },
    { s: "ASIANPAINT.NS", n: "Asian Paints" },
    { s: "MARUTI.NS", n: "Maruti Suzuki" },
    { s: "SUNPHARMA.NS", n: "Sun Pharma" },
    { s: "TITAN.NS", n: "Titan Company" },
    { s: "BAJFINANCE.NS", n: "Bajaj Finance" },
    { s: "WIPRO.NS", n: "Wipro Ltd" },
    { s: "ADANIENT.NS", n: "Adani Enterprises" },
    { s: "ADANIPORTS.NS", n: "Adani Ports" },
    { s: "KOTAKBANK.NS", n: "Kotak Mahindra Bank" },
    { s: "NTPC.NS", n: "NTPC Ltd" },
    { s: "ONGC.NS", n: "ONGC" },
    { s: "POWERGRID.NS", n: "Power Grid Corp" },
    { s: "ZOMATO.NS", n: "Zomato Ltd" },
    { s: "PAYTM.NS", n: "One 97 Communications" },
    { s: "DMART.NS", n: "Avenue Supermarts" },
    { s: "TATAPOWER.NS", n: "Tata Power" },
    { s: "IOB.NS", n: "Indian Overseas Bank" },
    { s: "DLF.NS", n: "DLF Ltd" },
    { s: "VBL.NS", n: "Varun Beverages" },
    { s: "SIEMENS.NS", n: "Siemens Ltd" },
    { s: "INDIGO.NS", n: "InterGlobe Aviation" },
    { s: "HAL.NS", n: "Hindustan Aeronautics" },
    { s: "BEL.NS", n: "Bharat Electronics" },
    { s: "COALINDIA.NS", n: "Coal India" },
    { s: "IOC.NS", n: "Indian Oil Corp" },
    { s: "EICHERMOT.NS", n: "Eicher Motors" },
    { s: "JSWSTEEL.NS", n: "JSW Steel" },
    { s: "GRASIM.NS", n: "Grasim Industries" },
    { s: "TECHM.NS", n: "Tech Mahindra" },
    { s: "ADANIGREEN.NS", n: "Adani Green Energy" },
    { s: "ADANIPOWER.NS", n: "Adani Power" },
    { s: "BAJAJ-AUTO.NS", n: "Bajaj Auto" },
    { s: "DIVISLAB.NS", n: "Divi's Laboratories" },
    { s: "DRREDDY.NS", n: "Dr. Reddy's Labs" },
    { s: "HCLTECH.NS", n: "HCL Technologies" },
    { s: "INDUSINDBK.NS", n: "IndusInd Bank" },

    // --- USA (S&P 100 Major + Tech) ---
    { s: "AAPL", n: "Apple Inc" },
    { s: "MSFT", n: "Microsoft Corp" },
    { s: "NVDA", n: "NVIDIA Corp" },
    { s: "GOOGL", n: "Alphabet Inc (Google)" },
    { s: "AMZN", n: "Amazon.com Inc" },
    { s: "META", n: "Meta Platforms" },
    { s: "TSLA", n: "Tesla Inc" },
    { s: "BRK-B", n: "Berkshire Hathaway" },
    { s: "LLY", n: "Eli Lilly" },
    { s: "AVGO", n: "Broadcom Inc" },
    { s: "JPM", n: "JPMorgan Chase" },
    { s: "V", n: "Visa Inc" },
    { s: "WMT", n: "Walmart Inc" },
    { s: "XOM", n: "Exxon Mobil" },
    { s: "MA", n: "Mastercard Inc" },
    { s: "CNH", n: "UnitedHealth Group" },
    { s: "PG", n: "Procter & Gamble" },
    { s: "JNJ", n: "Johnson & Johnson" },
    { s: "HD", n: "Home Depot" },
    { s: "MRK", n: "Merck & Co" },
    { s: "COST", n: "Costco Wholesale" },
    { s: "CVX", n: "Chevron Corp" },
    { s: "ABBV", n: "AbbVie Inc" },
    { s: "AMD", n: "Advanced Micro Devices" },
    { s: "NFLX", n: "Netflix Inc" },
    { s: "KO", n: "Coca-Cola" },
    { s: "PEP", n: "PepsiCo" },
    { s: "BAC", n: "Bank of America" },
    { s: "CSCO", n: "Cisco Systems" },
    { s: "CRM", n: "Salesforce" },
    { s: "MCD", n: "McDonald's" },
    { s: "TM", n: "Toyota Motor (ADR)" },
    { s: "NKE", n: "Nike Inc" },
    { s: "INTC", n: "Intel Corp" },
    { s: "QCOM", n: "Qualcomm" },
    { s: "TXN", n: "Texas Instruments" },
    { s: "IBM", n: "IBM Corp" },
    { s: "GE", n: "General Electric" },
    { s: "CAT", n: "Caterpillar Inc" },
    { s: "DIS", n: "Walt Disney Co" },
    { s: "BA", n: "Boeing Co" },
    { s: "VZ", n: "Verizon" },
    { s: "T", n: "AT&T Inc" },
    { s: "PFE", n: "Pfizer Inc" },

    // --- CRYPTO (Top 50) ---
    { s: "BTC-USD", n: "Bitcoin USD" },
    { s: "ETH-USD", n: "Ethereum USD" },
    { s: "SOL-USD", n: "Solana USD" },
    { s: "BNB-USD", n: "Binance Coin" },
    { s: "XRP-USD", n: "XRP" },
    { s: "ADA-USD", n: "Cardano" },
    { s: "DOGE-USD", n: "Dogecoin" },
    { s: "AVAX-USD", n: "Avalanche" },
    { s: "TRX-USD", n: "TRON" },
    { s: "DOT-USD", n: "Polkadot" },
    { s: "LINK-USD", n: "Chainlink" },
    { s: "MATIC-USD", n: "Polygon" },
    { s: "SHIB-USD", n: "Shiba Inu" },
    { s: "LTC-USD", n: "Litecoin" },
    { s: "BCH-USD", n: "Bitcoin Cash" },
    { s: "ATOM-USD", n: "Cosmos" },
    { s: "XMR-USD", n: "Monero" },
    { s: "ETC-USD", n: "Ethereum Classic" },
    { s: "XLM-USD", n: "Stellar" },
    { s: "NEAR-USD", n: "NEAR Protocol" },
    { s: "UNI-USD", n: "Uniswap" },
    { s: "FIL-USD", n: "Filecoin" },
    { s: "HBAR-USD", n: "Hedera" },
    { s: "APT-USD", n: "Aptos" },
    { s: "LDO-USD", n: "Lido DAO" },
    { s: "AR-USD", n: "Arweave" },
    { s: "INJ-USD", n: "Injective" },

    // --- GLOBAL INDICES & COMMODITIES ---
    { s: "^NSEI", n: "Nifty 50 Index (India)" },
    { s: "^BSESN", n: "Sensex Index (India)" },
    { s: "^GSPC", n: "S&P 500 (USA)" },
    { s: "^DJI", n: "Dow Jones Industrial" },
    { s: "^IXIC", n: "NASDAQ Composite" },
    { s: "^FTSE", n: "FTSE 100 (UK)" },
    { s: "^GDAX", n: "DAX Performance (Germany)" },
    { s: "^N225", n: "Nikkei 225 (Japan)" },
    { s: "^HSI", n: "Hang Seng Index (HK)" },
    { s: "000001.SS", n: "SSE Composite (China)" },
    { s: "GC=F", n: "Gold Futures" },
    { s: "SI=F", n: "Silver Futures" },
    { s: "CL=F", n: "Crude Oil WTI" },
    { s: "BZ=F", n: "Brent Crude Oil" },
    { s: "NG=F", n: "Natural Gas" },
    { s: "HG=F", n: "Copper" },

    // --- FOREX ---
    { s: "EURUSD=X", n: "EUR/USD" },
    { s: "USDJPY=X", n: "USD/JPY" },
    { s: "GBPUSD=X", n: "GBP/USD" },
    { s: "USDINR=X", n: "USD/INR" },
    { s: "EURINR=X", n: "EUR/INR" },
    { s: "GBPINR=X", n: "GBP/INR" },
    { s: "AUDUSD=X", n: "AUD/USD" },
    { s: "USDCAD=X", n: "USD/CAD" },

    // --- GLOBAL TECH & GIANTS ---
    { s: "BABA", n: "Alibaba Group" },
    { s: "TCEHY", n: "Tencent Holdings" },
    { s: "TSM", n: "Taiwan Semiconductor" },
    { s: "ASML", n: "ASML Holding" },
    { s: "NVO", n: "Novo Nordisk" },
    { s: "SHEL", n: "Shell PLC" },
    { s: "AZN", n: "AstraZeneca" },
    { s: "SAP", n: "SAP SE" },
    { s: "TM", n: "Toyota Motor" },
    { s: "SONY", n: "Sony Group" },
    { s: "SHOP", n: "Shopify" },
    { s: "SPOT", n: "Spotify" }
];
